//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalilakProject.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DalilakDatabaseEntities1 : DbContext
    {
        public DalilakDatabaseEntities1()
            : base("name=DalilakDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Suggeste> Suggestes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DrugAddictionRecoveryVilla> DrugAddictionRecoveryVillas { get; set; }
        public virtual DbSet<EmergencyPhoneNumber> EmergencyPhoneNumbers { get; set; }
        public virtual DbSet<FootballCourt> FootballCourts { get; set; }
        public virtual DbSet<GasStation> GasStations { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Pharmacy> Pharmacies { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
